import{S as v,i as l,a as x}from"./assets/vendor-DvP4Yn-N.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const f=document.querySelector(".loader"),g=document.querySelector(".gallery"),p=document.querySelector(".load-more-btn");function q({webformatURL:r,largeImageURL:e,tags:i,likes:a,views:t,comments:o,downloads:c}){const S=i.split(",").slice(0,3).join(", ");return`<li>
          <a href="${e}"><img src="${r}" alt="${S}" width="360" height="152" />
          <div class="thumb">
          <h2>Likes<span class="item-text">${a}</span></h2>
          <h2>Views<span class="item-text">${t}</span></h2>
          <h2>Comments<span class="item-text">${o}</span></h2>
          <h2>Downloads<span class="item-text">${c}</span></h2>
          </div>
          </a>
        </li>`}function P(r){return r.map(q).join(`
`)}const $=new v(".gallery a",{captionDelay:250,captionsData:"alt",captions:!0});function M(){g.innerHTML=""}function y(r){const e=P(r);g.insertAdjacentHTML("beforeend",e),$.refresh()}function L(){f.classList.remove("hidden")}function n(){f.classList.add("hidden")}function R(){p.classList.remove("hidden")}function u(){p.classList.add("hidden")}function w(r,e){if(r<e){R();return}else u(),l.info({message:"We're sorry, but you've reached the end of search results."})}const O="50463047-2395de4a1fa17e590ab2adb36",B="https://pixabay.com/api/";async function b(r,e){const i=new URLSearchParams({key:O,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15});return(await x.get(`${B}?${i}`)).data}let d=null,s=1,m=1;const h=document.querySelector(".form");n();u();h.addEventListener("submit",E);p.addEventListener("click",T);async function E(r){r.preventDefault(),d=r.target.elements["search-text"].value.trim(),s=1,M(),L();try{const e=await b(d,s);if(m=Math.ceil(e.totalHits/15),d===""){n(),l.warning({message:"Search field cannot be empty.",position:"topRight"}),u(),h.reset();return}if(!e.hits||e.hits.length===0){n(),l.warning({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"}),u(),h.reset();return}y(e.hits),n(),w(s,m),h.reset()}catch{n(),l.error({message:"Something went wrong!!!",position:"topRight"})}}async function T(){u();try{s++,L();const r=await b(d,s);y(r.hits),n(),window.scrollBy({top:document.querySelector("li").getBoundingClientRect().height*3,behavior:"smooth"}),w(s,m)}catch{n(),l.error({message:"Something went wrong!!!",position:"topRight"})}}
//# sourceMappingURL=index.js.map
