import{S as v,i as c,a as x}from"./assets/vendor-DvP4Yn-N.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&u(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const f=document.querySelector(".loader"),g=document.querySelector(".gallery"),p=document.querySelector(".load-more-btn");function q({webformatURL:r,largeImageURL:e,tags:s,likes:u,views:t,comments:o,downloads:i}){const S=s.split(",").slice(0,3).join(", ");return`<li>
          <a href="${e}"><img src="${r}" alt="${S}" width="360" height="152" />
          <div class="thumb">
          <h2>Likes<span class="item-text">${u}</span></h2>
          <h2>Views<span class="item-text">${t}</span></h2>
          <h2>Comments<span class="item-text">${o}</span></h2>
          <h2>Downloads<span class="item-text">${i}</span></h2>
          </div>
          </a>
        </li>`}function P(r){return r.map(q).join(`
`)}const $=new v(".gallery a",{captionDelay:250,captionsData:"alt",captions:!0});function M(){g.innerHTML=""}function y(r){const e=P(r);g.insertAdjacentHTML("beforeend",e),$.refresh()}function L(){f.classList.remove("hidden")}function n(){f.classList.add("hidden")}function R(){p.classList.remove("hidden")}function l(){p.classList.add("hidden")}function w(r,e){if(r<e){R();return}else l(),c.info({message:"We're sorry, but you've reached the end of search results."})}const O="50463047-2395de4a1fa17e590ab2adb36",B="https://pixabay.com/api/";async function b(r,e){const s=new URLSearchParams({key:O,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15});return await x.get(`${B}?${s}`)}let d=null,a=1,m=1;const h=document.querySelector(".form");n();l();h.addEventListener("submit",E);p.addEventListener("click",T);async function E(r){r.preventDefault(),d=r.target.elements["search-text"].value.trim(),a=1,M(),L();try{const e=await b(d,a);if(m=Math.ceil(e.data.totalHits/15),d===""){n(),c.warning({message:"Search field cannot be empty.",position:"topRight"}),l(),h.reset();return}if(!e.data.hits||e.data.hits.length===0){n(),c.warning({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"}),l(),h.reset();return}y(e.data.hits),n(),w(a,m),h.reset()}catch{n(),c.error({message:"Something went wrong!!!",position:"topRight"})}}async function T(){l();try{a++,L();const r=await b(d,a);y(r.data.hits),n(),window.scrollBy({top:document.querySelector("li").getBoundingClientRect().height*3,behavior:"smooth"}),w(a,m)}catch{n(),c.error({message:"Something went wrong!!!",position:"topRight"})}}
//# sourceMappingURL=index.js.map
